version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - FLASK_APP=rail_rank
      - FLASK_ENV=development
    command: sh -c "chmod 775 cron_init.sh && sh cron_init.sh && python3 -m flask --app rail_rank run --host 0.0.0.0 --debug"
